### ISSUE TITLE
Задания ко второй лабораторной

### ISSUE THREAD

**Issue by eligantRU** [eligantRU/oop#7]
- [x] Разделить элементы массива на половину максимального элемента [#20 + 10]
- [x] FindAndReplace [#50]
- [ ] Мини-словарь [#90 + 10 + 20]
- [x] Генератор простых чисел [#100]
- [ ] Парсер URL'ов [#80]
- [ ] Expand Template [#150 + 100]
